// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLQTDT.Api.Data;

#nullable disable

namespace QLQTDT.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260622174415_M5_RefreshTokenAndEvaluate")]
    partial class M5_RefreshTokenAndEvaluate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.BuocWorkflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("BatBuocDungSLA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("BatBuocGhiChu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("BatBuocKyTruocChuyenBuoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("BatBuocTaiLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("ChoPhepBoQua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("ChoPhepTuChoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("DonViKyHoSoId")
                        .HasColumnType("int");

                    b.Property<int?>("DonViXuLyId")
                        .HasColumnType("int");

                    b.Property<bool>("LaBuocJoin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LoaiBuoc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LoaiHan")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("CANH_BAO");

                    b.Property<string>("LyDoChonWorkflow")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaBuoc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("NhanhWorkflowId")
                        .HasColumnType("int");

                    b.Property<string>("NhomGiaiDoan")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NhomSongSong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SoNgayLapHoSo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("SoNgayXuLy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TenBuoc")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ThuTu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("VaiTroKyDuyetId")
                        .HasColumnType("int");

                    b.Property<int?>("VaiTroXuLyHoSoId")
                        .HasColumnType("int");

                    b.Property<bool>("WorkflowDuocChonThuCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("WorkflowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DonViKyHoSoId");

                    b.HasIndex("DonViXuLyId");

                    b.HasIndex("NhanhWorkflowId");

                    b.HasIndex("VaiTroKyDuyetId");

                    b.HasIndex("VaiTroXuLyHoSoId");

                    b.HasIndex("WorkflowId", "MaBuoc")
                        .IsUnique();

                    b.HasIndex("WorkflowId", "ThuTu");

                    b.ToTable("BuocWorkflow", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.ChiTietDeXuat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DeXuatId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("DonGiaDuToan")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("DonViTinh")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaVatTu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenVatTu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("ThanhTien")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("decimal(18,2)")
                        .HasComputedColumnSql("[SoLuong] * [DonGiaDuToan]");

                    b.HasKey("Id");

                    b.HasIndex("DeXuatId");

                    b.ToTable("ChiTietDeXuat", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.ChuyenTiepWorkflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("BatBuocGhiChu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("BatBuocTaiLieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("DenBuocId")
                        .HasColumnType("int");

                    b.Property<string>("DieuKien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DieuKienKichHoat")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("LUON");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HuongXuLyKhongDuyet")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("KetQuaApDung")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TuBuocId")
                        .HasColumnType("int");

                    b.Property<int?>("VaiTroApDungId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DenBuocId");

                    b.HasIndex("VaiTroApDungId");

                    b.HasIndex("TuBuocId", "HanhDong")
                        .IsUnique();

                    b.ToTable("ChuyenTiepWorkflow", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.DeXuatMuaSam", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("IdCongKhai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("KhoaPhongId")
                        .HasColumnType("int");

                    b.Property<string>("MaDeXuat")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayDeXuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("NguoiDeXuatId")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("TongDuToan")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("DRAFT");

                    b.HasKey("Id");

                    b.HasIndex("IdCongKhai")
                        .IsUnique();

                    b.HasIndex("KhoaPhongId");

                    b.HasIndex("MaDeXuat")
                        .IsUnique();

                    b.HasIndex("NguoiDeXuatId");

                    b.ToTable("DeXuatMuaSam", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.GoiThau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DeXuatId")
                        .HasColumnType("int");

                    b.Property<int?>("HinhThucId")
                        .HasColumnType("int");

                    b.Property<Guid>("IdCongKhai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int?>("KhoaPhongId")
                        .HasColumnType("int");

                    b.Property<string>("MaGoiThau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("NganSach")
                        .HasColumnType("decimal(18,0)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("NguoiTaoId")
                        .HasColumnType("int");

                    b.Property<string>("TenGoiThau")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TheoDoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("DU_THAO");

                    b.Property<bool>("TrangThaiHoatDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("WorkflowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCongKhai")
                        .IsUnique();

                    b.HasIndex("MaGoiThau")
                        .IsUnique();

                    b.ToTable("GoiThau", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.HinhThucDauThau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("HanMucToiDa")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("MaHinhThuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenHinhThuc")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("TrangThaiHoatDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("MaHinhThuc")
                        .IsUnique();

                    b.ToTable("HinhThucDauThau", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.HoSoDuThau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("DiemDanhGia")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("GiaDuThau")
                        .HasColumnType("decimal(18,0)");

                    b.Property<decimal?>("GiaTrungThau")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("GoiThauId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("NgayNop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("NhaThauId")
                        .HasColumnType("int");

                    b.Property<string>("NhanXet")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("NhaThauId");

                    b.HasIndex("GoiThauId", "NhaThauId")
                        .IsUnique();

                    b.ToTable("HoSoDuThau", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.HoSoNangLuc", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DuongDanFile")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("LoaiTaiLieu")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("NgayHetHan")
                        .HasColumnType("date");

                    b.Property<int>("NhaThauId")
                        .HasColumnType("int");

                    b.Property<string>("TenFile")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("NhaThauId");

                    b.ToTable("HoSoNangLuc", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.HopDong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GoiThauId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("NgayKy")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("SoHopDong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TongGiaTri")
                        .HasColumnType("decimal(18,0)");

                    b.HasKey("Id");

                    b.HasIndex("GoiThauId")
                        .IsUnique();

                    b.HasIndex("SoHopDong")
                        .IsUnique();

                    b.ToTable("HopDong", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.IntegrationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("HeThong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LoaiDongBo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequestPayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsePayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianDongBo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("IntegrationLog", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.KhoaPhong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("IdCongKhai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("MaKhoaPhong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenKhoaPhong")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("IdCongKhai")
                        .IsUnique();

                    b.HasIndex("MaKhoaPhong")
                        .IsUnique();

                    b.ToTable("KhoaPhong", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.LichSuTrangThaiGoiThau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GoiThauId")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiThayDoiId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianThayDoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("TrangThaiCu")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TrangThaiMoi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiThayDoiId");

                    b.HasIndex("GoiThauId", "ThoiGianThayDoi");

                    b.ToTable("LichSuTrangThaiGoiThau", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.LoginLockout", b =>
                {
                    b.Property<string>("Identifier")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastFailedAttempt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("Identifier");

                    b.ToTable("LoginLockout", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("IdCongKhai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("NgayDangNhapCuoi")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThaiHoatDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasFilter("[GoogleId] IS NOT NULL");

                    b.HasIndex("IdCongKhai")
                        .IsUnique();

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.NguoiDungKhoaPhongVaiTro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("KhoaPhongId")
                        .HasColumnType("int");

                    b.Property<bool>("LaChinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<int>("VaiTroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KhoaPhongId");

                    b.HasIndex("VaiTroId");

                    b.HasIndex("NguoiDungId", "KhoaPhongId", "VaiTroId")
                        .IsUnique()
                        .HasFilter("[KhoaPhongId] IS NOT NULL");

                    b.ToTable("NguoiDung_KhoaPhong_VaiTro", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.NhaThau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaSoThue")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NguoiDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenCongTy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("TrangThaiHoatDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("MaSoThue")
                        .IsUnique();

                    b.ToTable("NhaThau", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.NhanhWorkflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuocDauTienId")
                        .HasColumnType("int");

                    b.Property<int?>("DonViXuLyId")
                        .HasColumnType("int");

                    b.Property<string>("LoaiHan")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("CANH_BAO");

                    b.Property<string>("MaNhanh")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NhomNhanhWorkflowId")
                        .HasColumnType("int");

                    b.Property<string>("TenNhanh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("ThoiHanNgay")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.Property<int?>("VaiTroXuLyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuocDauTienId");

                    b.HasIndex("DonViXuLyId");

                    b.HasIndex("VaiTroXuLyId");

                    b.HasIndex("NhomNhanhWorkflowId", "MaNhanh")
                        .IsUnique();

                    b.HasIndex("NhomNhanhWorkflowId", "ThuTu");

                    b.ToTable("NhanhWorkflow", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.NhomNhanhWorkflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuocSauHopNhatId")
                        .HasColumnType("int");

                    b.Property<int>("BuocTachNhanhId")
                        .HasColumnType("int");

                    b.Property<string>("DieuKienHopNhat")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("ALL");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("SoNhanhHopNhatToiThieu")
                        .HasColumnType("int");

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuocSauHopNhatId");

                    b.HasIndex("BuocTachNhanhId");

                    b.HasIndex("WorkflowId", "BuocTachNhanhId");

                    b.ToTable("NhomNhanhWorkflow", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.NhomVaiTro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("DoUuTien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("MaNhom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenNhom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("MaNhom")
                        .IsUnique();

                    b.ToTable("NhomVaiTro", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.PasswordResetToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Used")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("PasswordResetToken", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.Quyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MaQuyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("MaQuyen")
                        .IsUnique();

                    b.ToTable("Quyen", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.TaiLieuHoSo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("DuongDanFtp")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("GoiThauId")
                        .HasColumnType("int");

                    b.Property<int?>("HoSoDuThauId")
                        .HasColumnType("int");

                    b.Property<int?>("HopDongId")
                        .HasColumnType("int");

                    b.Property<long>("KichThuoc")
                        .HasColumnType("bigint");

                    b.Property<string>("LoaiTaiLieu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("NguoiUploadId")
                        .HasColumnType("int");

                    b.Property<string>("TenFile")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("GoiThauId");

                    b.HasIndex("HoSoDuThauId");

                    b.HasIndex("HopDongId");

                    b.ToTable("TaiLieuHoSo", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.ThongBao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaDoc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("GoiThauId")
                        .HasColumnType("int");

                    b.Property<Guid>("IdCongKhai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("LoaiThongBao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayDoc")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("UrlDieuHuong")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("GoiThauId");

                    b.HasIndex("IdCongKhai")
                        .IsUnique();

                    b.HasIndex("NguoiDungId", "DaDoc");

                    b.ToTable("ThongBao", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.VaiTro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MaVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NhomVaiTroId")
                        .HasColumnType("int");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("MaVaiTro")
                        .IsUnique();

                    b.HasIndex("NhomVaiTroId");

                    b.HasIndex("TenVaiTro")
                        .IsUnique();

                    b.ToTable("VaiTro", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.VaiTroQuyen", b =>
                {
                    b.Property<int>("VaiTroId")
                        .HasColumnType("int");

                    b.Property<int>("QuyenId")
                        .HasColumnType("int");

                    b.HasKey("VaiTroId", "QuyenId");

                    b.HasIndex("QuyenId");

                    b.ToTable("VaiTro_Quyen", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.Workflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HinhThucId")
                        .HasColumnType("int");

                    b.Property<bool>("LaQuyTrinhChuan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LoaiHinhDauThau")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaWorkflow")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTaNgan")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PhamViApDung")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TenWorkflow")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("TrangThaiHoatDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("HinhThucId");

                    b.HasIndex("MaWorkflow")
                        .IsUnique();

                    b.ToTable("Workflow", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.WorkflowActionHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NguoiThucHienId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<long>("WorkflowInstanceId")
                        .HasColumnType("bigint");

                    b.Property<long?>("WorkflowStepInstanceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowInstanceId");

                    b.HasIndex("WorkflowStepInstanceId");

                    b.ToTable("WorkflowActionHistory", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.WorkflowAssignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("DaXuLy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("NgayGiao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("NgayXuLy")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDuocGiaoId")
                        .HasColumnType("int");

                    b.Property<string>("PhieuKyDuyet")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("WorkflowStepInstanceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDuocGiaoId");

                    b.HasIndex("WorkflowStepInstanceId", "NguoiDuocGiaoId")
                        .IsUnique();

                    b.ToTable("WorkflowAssignment", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.WorkflowInstance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("BuocHienTaiId")
                        .HasColumnType("int");

                    b.Property<int>("GoiThauId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBatDau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("NgayHoanThanh")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuocHienTaiId");

                    b.HasIndex("GoiThauId");

                    b.HasIndex("WorkflowId");

                    b.ToTable("WorkflowInstance", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.WorkflowStepInstance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("BuocWorkflowId")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime?>("HanXuLy")
                        .HasColumnType("datetime2");

                    b.Property<string>("KetQua")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LyDoKhongDuyet")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("NgayBatDau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("NgayHoanThanh")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKyDuyet")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayXuLy")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiKyDuyetId")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiXuLyId")
                        .HasColumnType("int");

                    b.Property<string>("PhaHienTai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("LAP_HO_SO");

                    b.Property<bool?>("QuaHan")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TaiLieuDinhKem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("DANG_XU_LY");

                    b.Property<long>("WorkflowInstanceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BuocWorkflowId");

                    b.HasIndex("NguoiKyDuyetId");

                    b.HasIndex("NguoiXuLyId");

                    b.HasIndex("WorkflowInstanceId");

                    b.ToTable("WorkflowStepInstance", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.WorkflowVersionHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("NguoiTaoId")
                        .HasColumnType("int");

                    b.Property<string>("SnapshotData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("int");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NguoiTaoId");

                    b.HasIndex("WorkflowId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("WorkflowVersionHistory", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.NhatKyKiemToan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("GoiThauId")
                        .HasColumnType("bigint");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MoTaChiTiet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NguoiThucHienId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianThucHien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.ToTable("NhatKyKiemToan", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.BuocWorkflow", b =>
                {
                    b.HasOne("QLQTDT.Api.Models.Entities.KhoaPhong", "DonViKyHoSo")
                        .WithMany()
                        .HasForeignKey("DonViKyHoSoId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QLQTDT.Api.Models.Entities.KhoaPhong", "DonViXuLy")
                        .WithMany()
                        .HasForeignKey("DonViXuLyId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QLQTDT.Api.Models.Entities.NhanhWorkflow", "NhanhWorkflow")
                        .WithMany("BuocWorkflows")
                        .HasForeignKey("NhanhWorkflowId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("QLQTDT.Api.Models.Entities.VaiTro", "VaiTroKyDuyet")
                        .WithMany()
                        .HasForeignKey("VaiTroKyDuyetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QLQTDT.Api.Models.Entities.VaiTro", "VaiTroXuLyHoSo")
                        .WithMany()
                        .HasForeignKey("VaiTroXuLyHoSoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QLQTDT.Api.Models.Entities.Workflow", "Workflow")
                        .WithMany("BuocWorkflows")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonViKyHoSo");

                    b.Navigation("DonViXuLy");

                    b.Navigation("NhanhWorkflow");

                    b.Navigation("VaiTroKyDuyet");

                    b.Navigation("VaiTroXuLyHoSo");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.ChiTietDeXuat", b =>
                {
                    b.HasOne("QLQTDT.Api.Models.Entities.DeXuatMuaSam", "DeXuat")
                        .WithMany("ChiTiet")
                        .HasForeignKey("DeXuatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeXuat");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.ChuyenTiepWorkflow", b =>
                {
                    b.HasOne("QLQTDT.Api.Models.Entities.BuocWorkflow", "DenBuoc")
                        .WithMany("ChuyenTiepDen")
                        .HasForeignKey("DenBuocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLQTDT.Api.Models.Entities.BuocWorkflow", "TuBuoc")
                        .WithMany("ChuyenTiepDi")
                        .HasForeignKey("TuBuocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLQTDT.Api.Models.Entities.VaiTro", "VaiTroApDung")
                        .WithMany()
                        .HasForeignKey("VaiTroApDungId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DenBuoc");

                    b.Navigation("TuBuoc");

                    b.Navigation("VaiTroApDung");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.DeXuatMuaSam", b =>
                {
                    b.HasOne("QLQTDT.Api.Models.Entities.KhoaPhong", "KhoaPhong")
                        .WithMany()
                        .HasForeignKey("KhoaPhongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLQTDT.Api.Models.Entities.NguoiDung", "NguoiDeXuat")
                        .WithMany()
                        .HasForeignKey("NguoiDeXuatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoaPhong");

                    b.Navigation("NguoiDeXuat");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.HoSoDuThau", b =>
                {
                    b.HasOne("QLQTDT.Api.Models.Entities.GoiThau", "GoiThau")
                        .WithMany()
                        .HasForeignKey("GoiThauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLQTDT.Api.Models.Entities.NhaThau", "NhaThau")
                        .WithMany()
                        .HasForeignKey("NhaThauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GoiThau");

                    b.Navigation("NhaThau");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.HoSoNangLuc", b =>
                {
                    b.HasOne("QLQTDT.Api.Models.Entities.NhaThau", "NhaThau")
                        .WithMany()
                        .HasForeignKey("NhaThauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhaThau");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.HopDong", b =>
                {
                    b.HasOne("QLQTDT.Api.Models.Entities.GoiThau", "GoiThau")
                        .WithMany()
                        .HasForeignKey("GoiThauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GoiThau");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.LichSuTrangThaiGoiThau", b =>
                {
                    b.HasOne("QLQTDT.Api.Models.Entities.GoiThau", null)
                        .WithMany()
                        .HasForeignKey("GoiThauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLQTDT.Api.Models.Entities.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("NguoiThayDoiId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.NguoiDungKhoaPhongVaiTro", b =>
                {
                    b.HasOne("QLQTDT.Api.Models.Entities.KhoaPhong", "KhoaPhong")
                        .WithMany("NguoiDungKhoaPhongVaiTros")
                        .HasForeignKey("KhoaPhongId");

                    b.HasOne("QLQTDT.Api.Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany("NguoiDungKhoaPhongVaiTros")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLQTDT.Api.Models.Entities.VaiTro", "VaiTro")
                        .WithMany("NguoiDungKhoaPhongVaiTros")
                        .HasForeignKey("VaiTroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoaPhong");

                    b.Navigation("NguoiDung");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.NhanhWorkflow", b =>
                {
                    b.HasOne("QLQTDT.Api.Models.Entities.BuocWorkflow", "BuocDauTien")
                        .WithMany()
                        .HasForeignKey("BuocDauTienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLQTDT.Api.Models.Entities.KhoaPhong", "DonViXuLy")
                        .WithMany()
                        .HasForeignKey("DonViXuLyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QLQTDT.Api.Models.Entities.NhomNhanhWorkflow", "NhomNhanhWorkflow")
                        .WithMany("Nhanhs")
                        .HasForeignKey("NhomNhanhWorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLQTDT.Api.Models.Entities.VaiTro", "VaiTroXuLy")
                        .WithMany()
                        .HasForeignKey("VaiTroXuLyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BuocDauTien");

                    b.Navigation("DonViXuLy");

                    b.Navigation("NhomNhanhWorkflow");

                    b.Navigation("VaiTroXuLy");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.NhomNhanhWorkflow", b =>
                {
                    b.HasOne("QLQTDT.Api.Models.Entities.BuocWorkflow", "BuocSauHopNhat")
                        .WithMany()
                        .HasForeignKey("BuocSauHopNhatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLQTDT.Api.Models.Entities.BuocWorkflow", "BuocTachNhanh")
                        .WithMany()
                        .HasForeignKey("BuocTachNhanhId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLQTDT.Api.Models.Entities.Workflow", "Workflow")
                        .WithMany("NhomNhanhWorkflows")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuocSauHopNhat");

                    b.Navigation("BuocTachNhanh");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("QLQTDT.Api.Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.RefreshToken", b =>
                {
                    b.HasOne("QLQTDT.Api.Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.TaiLieuHoSo", b =>
                {
                    b.HasOne("QLQTDT.Api.Models.Entities.GoiThau", null)
                        .WithMany()
                        .HasForeignKey("GoiThauId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("QLQTDT.Api.Models.Entities.HoSoDuThau", null)
                        .WithMany("TaiLieus")
                        .HasForeignKey("HoSoDuThauId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QLQTDT.Api.Models.Entities.HopDong", null)
                        .WithMany("TaiLieus")
                        .HasForeignKey("HopDongId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.ThongBao", b =>
                {
                    b.HasOne("QLQTDT.Api.Models.Entities.GoiThau", "GoiThau")
                        .WithMany()
                        .HasForeignKey("GoiThauId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QLQTDT.Api.Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GoiThau");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.VaiTro", b =>
                {
                    b.HasOne("QLQTDT.Api.Models.Entities.NhomVaiTro", "NhomVaiTro")
                        .WithMany("VaiTros")
                        .HasForeignKey("NhomVaiTroId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("NhomVaiTro");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.VaiTroQuyen", b =>
                {
                    b.HasOne("QLQTDT.Api.Models.Entities.Quyen", "Quyen")
                        .WithMany("VaiTroQuyens")
                        .HasForeignKey("QuyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLQTDT.Api.Models.Entities.VaiTro", "VaiTro")
                        .WithMany("VaiTroQuyens")
                        .HasForeignKey("VaiTroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quyen");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.Workflow", b =>
                {
                    b.HasOne("QLQTDT.Api.Models.Entities.HinhThucDauThau", "HinhThuc")
                        .WithMany("Workflows")
                        .HasForeignKey("HinhThucId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HinhThuc");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.WorkflowActionHistory", b =>
                {
                    b.HasOne("QLQTDT.Api.Models.Entities.WorkflowInstance", "WorkflowInstance")
                        .WithMany("WorkflowActionHistories")
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLQTDT.Api.Models.Entities.WorkflowStepInstance", "WorkflowStepInstance")
                        .WithMany()
                        .HasForeignKey("WorkflowStepInstanceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("WorkflowInstance");

                    b.Navigation("WorkflowStepInstance");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.WorkflowAssignment", b =>
                {
                    b.HasOne("QLQTDT.Api.Models.Entities.NguoiDung", "NguoiDuocGiao")
                        .WithMany()
                        .HasForeignKey("NguoiDuocGiaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLQTDT.Api.Models.Entities.WorkflowStepInstance", "WorkflowStepInstance")
                        .WithMany("WorkflowAssignments")
                        .HasForeignKey("WorkflowStepInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDuocGiao");

                    b.Navigation("WorkflowStepInstance");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.WorkflowInstance", b =>
                {
                    b.HasOne("QLQTDT.Api.Models.Entities.BuocWorkflow", "BuocHienTai")
                        .WithMany()
                        .HasForeignKey("BuocHienTaiId");

                    b.HasOne("QLQTDT.Api.Models.Entities.GoiThau", "GoiThau")
                        .WithMany()
                        .HasForeignKey("GoiThauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLQTDT.Api.Models.Entities.Workflow", "Workflow")
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuocHienTai");

                    b.Navigation("GoiThau");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.WorkflowStepInstance", b =>
                {
                    b.HasOne("QLQTDT.Api.Models.Entities.BuocWorkflow", "BuocWorkflow")
                        .WithMany("WorkflowStepInstances")
                        .HasForeignKey("BuocWorkflowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLQTDT.Api.Models.Entities.NguoiDung", "NguoiKyDuyet")
                        .WithMany()
                        .HasForeignKey("NguoiKyDuyetId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QLQTDT.Api.Models.Entities.NguoiDung", "NguoiXuLy")
                        .WithMany()
                        .HasForeignKey("NguoiXuLyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QLQTDT.Api.Models.Entities.WorkflowInstance", "WorkflowInstance")
                        .WithMany("WorkflowStepInstances")
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuocWorkflow");

                    b.Navigation("NguoiKyDuyet");

                    b.Navigation("NguoiXuLy");

                    b.Navigation("WorkflowInstance");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.WorkflowVersionHistory", b =>
                {
                    b.HasOne("QLQTDT.Api.Models.Entities.NguoiDung", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QLQTDT.Api.Models.Entities.Workflow", "Workflow")
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiTao");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.BuocWorkflow", b =>
                {
                    b.Navigation("ChuyenTiepDen");

                    b.Navigation("ChuyenTiepDi");

                    b.Navigation("WorkflowStepInstances");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.DeXuatMuaSam", b =>
                {
                    b.Navigation("ChiTiet");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.HinhThucDauThau", b =>
                {
                    b.Navigation("Workflows");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.HoSoDuThau", b =>
                {
                    b.Navigation("TaiLieus");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.HopDong", b =>
                {
                    b.Navigation("TaiLieus");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.KhoaPhong", b =>
                {
                    b.Navigation("NguoiDungKhoaPhongVaiTros");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.NguoiDung", b =>
                {
                    b.Navigation("NguoiDungKhoaPhongVaiTros");

                    b.Navigation("PasswordResetTokens");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.NhanhWorkflow", b =>
                {
                    b.Navigation("BuocWorkflows");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.NhomNhanhWorkflow", b =>
                {
                    b.Navigation("Nhanhs");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.NhomVaiTro", b =>
                {
                    b.Navigation("VaiTros");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.Quyen", b =>
                {
                    b.Navigation("VaiTroQuyens");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.VaiTro", b =>
                {
                    b.Navigation("NguoiDungKhoaPhongVaiTros");

                    b.Navigation("VaiTroQuyens");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.Workflow", b =>
                {
                    b.Navigation("BuocWorkflows");

                    b.Navigation("NhomNhanhWorkflows");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.WorkflowInstance", b =>
                {
                    b.Navigation("WorkflowActionHistories");

                    b.Navigation("WorkflowStepInstances");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.WorkflowStepInstance", b =>
                {
                    b.Navigation("WorkflowAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
