// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLQTDT.Api.Data;

#nullable disable

namespace QLQTDT.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260612140909_CreateMissingWorkflowRuntimeTables")]
    partial class CreateMissingWorkflowRuntimeTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.BuocWorkflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("ChoPhepBoQua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("ChoPhepTuChoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("KhoaPhongXuLyId")
                        .HasColumnType("int");

                    b.Property<string>("LoaiBuoc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LyDoChonWorkflow")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaBuoc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("SoNgaySLA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TenBuoc")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("VaiTroXuLyId")
                        .HasColumnType("int");

                    b.Property<bool>("WorkflowDuocChonThuCong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("WorkflowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KhoaPhongXuLyId");

                    b.HasIndex("VaiTroXuLyId");

                    b.HasIndex("WorkflowId", "MaBuoc")
                        .IsUnique();

                    b.ToTable("BuocWorkflow", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.ChuyenTiepWorkflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DenBuocId")
                        .HasColumnType("int");

                    b.Property<string>("DieuKien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TuBuocId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DenBuocId");

                    b.HasIndex("TuBuocId", "HanhDong")
                        .IsUnique();

                    b.ToTable("ChuyenTiepWorkflow", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.GoiThau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DeXuatId")
                        .HasColumnType("int");

                    b.Property<int?>("HinhThucId")
                        .HasColumnType("int");

                    b.Property<Guid>("IdCongKhai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int?>("KhoaPhongId")
                        .HasColumnType("int");

                    b.Property<string>("MaGoiThau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal?>("NganSach")
                        .HasColumnType("decimal(18,0)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("NguoiTaoId")
                        .HasColumnType("int");

                    b.Property<string>("TenGoiThau")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("DU_THAO");

                    b.Property<bool>("TrangThaiHoatDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("WorkflowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCongKhai")
                        .IsUnique();

                    b.HasIndex("MaGoiThau")
                        .IsUnique();

                    b.ToTable("GoiThau", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.HinhThucDauThau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("HanMucToiDa")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("MaHinhThuc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenHinhThuc")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("TrangThaiHoatDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("MaHinhThuc")
                        .IsUnique();

                    b.ToTable("HinhThucDauThau", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.IntegrationLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("HeThong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LoaiDongBo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequestPayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponsePayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ThoiGianDongBo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("IntegrationLog", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.KhoaPhong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("IdCongKhai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("MaKhoaPhong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenKhoaPhong")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("IdCongKhai")
                        .IsUnique();

                    b.HasIndex("MaKhoaPhong")
                        .IsUnique();

                    b.ToTable("KhoaPhong", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.LoginLockout", b =>
                {
                    b.Property<string>("Identifier")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastFailedAttempt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("Identifier");

                    b.ToTable("LoginLockout", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("IdCongKhai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayCapNhat")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("NgayDangNhapCuoi")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThaiHoatDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasFilter("[GoogleId] IS NOT NULL");

                    b.HasIndex("IdCongKhai")
                        .IsUnique();

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.NguoiDungKhoaPhongVaiTro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("KhoaPhongId")
                        .HasColumnType("int");

                    b.Property<bool>("LaChinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<int>("VaiTroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KhoaPhongId");

                    b.HasIndex("VaiTroId");

                    b.HasIndex("NguoiDungId", "KhoaPhongId", "VaiTroId")
                        .IsUnique()
                        .HasFilter("[KhoaPhongId] IS NOT NULL");

                    b.ToTable("NguoiDung_KhoaPhong_VaiTro", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.NhaThau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MaSoThue")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NguoiDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenCongTy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("TrangThaiHoatDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("MaSoThue")
                        .IsUnique();

                    b.ToTable("NhaThau", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.PasswordResetToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Used")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("PasswordResetToken", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.Quyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MaQuyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("MaQuyen")
                        .IsUnique();

                    b.ToTable("Quyen", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.VaiTro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MaVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("MaVaiTro")
                        .IsUnique();

                    b.HasIndex("TenVaiTro")
                        .IsUnique();

                    b.ToTable("VaiTro", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.VaiTroQuyen", b =>
                {
                    b.Property<int>("VaiTroId")
                        .HasColumnType("int");

                    b.Property<int>("QuyenId")
                        .HasColumnType("int");

                    b.HasKey("VaiTroId", "QuyenId");

                    b.HasIndex("QuyenId");

                    b.ToTable("VaiTro_Quyen", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.Workflow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HinhThucId")
                        .HasColumnType("int");

                    b.Property<string>("MaWorkflow")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenWorkflow")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("TrangThaiHoatDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("HinhThucId");

                    b.HasIndex("MaWorkflow")
                        .IsUnique();

                    b.ToTable("Workflow", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.WorkflowActionHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NguoiThucHienId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<long>("WorkflowInstanceId")
                        .HasColumnType("bigint");

                    b.Property<long?>("WorkflowStepInstanceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowInstanceId");

                    b.HasIndex("WorkflowStepInstanceId");

                    b.ToTable("WorkflowActionHistory", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.WorkflowAssignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("DaXuLy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("NgayGiao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("NgayXuLy")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiDuocGiaoId")
                        .HasColumnType("int");

                    b.Property<long>("WorkflowStepInstanceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("NguoiDuocGiaoId");

                    b.HasIndex("WorkflowStepInstanceId", "NguoiDuocGiaoId")
                        .IsUnique();

                    b.ToTable("WorkflowAssignment", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.WorkflowInstance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("BuocHienTaiId")
                        .HasColumnType("int");

                    b.Property<int>("GoiThauId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayBatDau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("NgayHoanThanh")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("WorkflowId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuocHienTaiId");

                    b.HasIndex("GoiThauId");

                    b.HasIndex("WorkflowId");

                    b.ToTable("WorkflowInstance", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.WorkflowStepInstance", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("BuocWorkflowId")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("NgayBatDau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("NgayHoanThanh")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiXuLyId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("PENDING");

                    b.Property<long>("WorkflowInstanceId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BuocWorkflowId");

                    b.HasIndex("NguoiXuLyId");

                    b.HasIndex("WorkflowInstanceId");

                    b.ToTable("WorkflowStepInstance", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.NhatKyKiemToan", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("GoiThauId")
                        .HasColumnType("bigint");

                    b.Property<string>("HanhDong")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MoTaChiTiet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NguoiThucHienId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ThoiGianThucHien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.ToTable("NhatKyKiemToan", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.BuocWorkflow", b =>
                {
                    b.HasOne("QLQTDT.Api.Models.Entities.KhoaPhong", "KhoaPhongXuLy")
                        .WithMany()
                        .HasForeignKey("KhoaPhongXuLyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QLQTDT.Api.Models.Entities.VaiTro", "VaiTroXuLy")
                        .WithMany()
                        .HasForeignKey("VaiTroXuLyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QLQTDT.Api.Models.Entities.Workflow", "Workflow")
                        .WithMany("BuocWorkflows")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoaPhongXuLy");

                    b.Navigation("VaiTroXuLy");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.ChuyenTiepWorkflow", b =>
                {
                    b.HasOne("QLQTDT.Api.Models.Entities.BuocWorkflow", "DenBuoc")
                        .WithMany("ChuyenTiepDen")
                        .HasForeignKey("DenBuocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLQTDT.Api.Models.Entities.BuocWorkflow", "TuBuoc")
                        .WithMany("ChuyenTiepDi")
                        .HasForeignKey("TuBuocId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DenBuoc");

                    b.Navigation("TuBuoc");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.NguoiDungKhoaPhongVaiTro", b =>
                {
                    b.HasOne("QLQTDT.Api.Models.Entities.KhoaPhong", "KhoaPhong")
                        .WithMany("NguoiDungKhoaPhongVaiTros")
                        .HasForeignKey("KhoaPhongId");

                    b.HasOne("QLQTDT.Api.Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany("NguoiDungKhoaPhongVaiTros")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLQTDT.Api.Models.Entities.VaiTro", "VaiTro")
                        .WithMany("NguoiDungKhoaPhongVaiTros")
                        .HasForeignKey("VaiTroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoaPhong");

                    b.Navigation("NguoiDung");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("QLQTDT.Api.Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.VaiTroQuyen", b =>
                {
                    b.HasOne("QLQTDT.Api.Models.Entities.Quyen", "Quyen")
                        .WithMany("VaiTroQuyens")
                        .HasForeignKey("QuyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLQTDT.Api.Models.Entities.VaiTro", "VaiTro")
                        .WithMany("VaiTroQuyens")
                        .HasForeignKey("VaiTroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quyen");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.Workflow", b =>
                {
                    b.HasOne("QLQTDT.Api.Models.Entities.HinhThucDauThau", "HinhThucDauThau")
                        .WithMany("Workflows")
                        .HasForeignKey("HinhThucId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HinhThucDauThau");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.WorkflowActionHistory", b =>
                {
                    b.HasOne("QLQTDT.Api.Models.Entities.WorkflowInstance", "WorkflowInstance")
                        .WithMany("WorkflowActionHistories")
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLQTDT.Api.Models.Entities.WorkflowStepInstance", "WorkflowStepInstance")
                        .WithMany()
                        .HasForeignKey("WorkflowStepInstanceId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("WorkflowInstance");

                    b.Navigation("WorkflowStepInstance");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.WorkflowAssignment", b =>
                {
                    b.HasOne("QLQTDT.Api.Models.Entities.NguoiDung", "NguoiDuocGiao")
                        .WithMany()
                        .HasForeignKey("NguoiDuocGiaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLQTDT.Api.Models.Entities.WorkflowStepInstance", "WorkflowStepInstance")
                        .WithMany("WorkflowAssignments")
                        .HasForeignKey("WorkflowStepInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDuocGiao");

                    b.Navigation("WorkflowStepInstance");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.WorkflowInstance", b =>
                {
                    b.HasOne("QLQTDT.Api.Models.Entities.BuocWorkflow", "BuocHienTai")
                        .WithMany()
                        .HasForeignKey("BuocHienTaiId");

                    b.HasOne("QLQTDT.Api.Models.Entities.GoiThau", "GoiThau")
                        .WithMany()
                        .HasForeignKey("GoiThauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLQTDT.Api.Models.Entities.Workflow", "Workflow")
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuocHienTai");

                    b.Navigation("GoiThau");

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.WorkflowStepInstance", b =>
                {
                    b.HasOne("QLQTDT.Api.Models.Entities.BuocWorkflow", "BuocWorkflow")
                        .WithMany("WorkflowStepInstances")
                        .HasForeignKey("BuocWorkflowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QLQTDT.Api.Models.Entities.NguoiDung", "NguoiXuLy")
                        .WithMany()
                        .HasForeignKey("NguoiXuLyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QLQTDT.Api.Models.Entities.WorkflowInstance", "WorkflowInstance")
                        .WithMany("WorkflowStepInstances")
                        .HasForeignKey("WorkflowInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuocWorkflow");

                    b.Navigation("NguoiXuLy");

                    b.Navigation("WorkflowInstance");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.BuocWorkflow", b =>
                {
                    b.Navigation("ChuyenTiepDen");

                    b.Navigation("ChuyenTiepDi");

                    b.Navigation("WorkflowStepInstances");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.HinhThucDauThau", b =>
                {
                    b.Navigation("Workflows");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.KhoaPhong", b =>
                {
                    b.Navigation("NguoiDungKhoaPhongVaiTros");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.NguoiDung", b =>
                {
                    b.Navigation("NguoiDungKhoaPhongVaiTros");

                    b.Navigation("PasswordResetTokens");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.Quyen", b =>
                {
                    b.Navigation("VaiTroQuyens");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.VaiTro", b =>
                {
                    b.Navigation("NguoiDungKhoaPhongVaiTros");

                    b.Navigation("VaiTroQuyens");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.Workflow", b =>
                {
                    b.Navigation("BuocWorkflows");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.WorkflowInstance", b =>
                {
                    b.Navigation("WorkflowActionHistories");

                    b.Navigation("WorkflowStepInstances");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.WorkflowStepInstance", b =>
                {
                    b.Navigation("WorkflowAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
