// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QLQTDT.Api.Data;

#nullable disable

namespace QLQTDT.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.KhoaPhong", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("IdCongKhai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("MaKhoaPhong")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenKhoaPhong")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("IdCongKhai")
                        .IsUnique();

                    b.HasIndex("MaKhoaPhong")
                        .IsUnique();

                    b.ToTable("KhoaPhong", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.LoginLockout", b =>
                {
                    b.Property<string>("Identifier")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastFailedAttempt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2(3)");

                    b.HasKey("Identifier");

                    b.ToTable("LoginLockout", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GoogleId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("IdCongKhai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("MatKhauHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayTao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("TrangThaiHoatDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleId")
                        .IsUnique()
                        .HasFilter("[GoogleId] IS NOT NULL");

                    b.HasIndex("IdCongKhai")
                        .IsUnique();

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.NguoiDungKhoaPhongVaiTro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("KhoaPhongId")
                        .HasColumnType("int");

                    b.Property<bool>("LaChinh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<int>("VaiTroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KhoaPhongId");

                    b.HasIndex("VaiTroId");

                    b.HasIndex("NguoiDungId", "KhoaPhongId", "VaiTroId")
                        .IsUnique()
                        .HasFilter("[KhoaPhongId] IS NOT NULL");

                    b.ToTable("NguoiDung_KhoaPhong_VaiTro", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.NhaThau", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaSoThue")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NguoiDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("TenCongTy")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("TrangThaiHoatDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.HasIndex("MaSoThue")
                        .IsUnique();

                    b.HasIndex("NguoiDungId");

                    b.ToTable("NhaThau", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.PasswordResetToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("NguoiDungId")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Used")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("NguoiDungId");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("PasswordResetToken", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.Quyen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MaQuyen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenQuyen")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("MaQuyen")
                        .IsUnique();

                    b.ToTable("Quyen", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.VaiTro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaXoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("TenVaiTro")
                        .IsUnique();

                    b.ToTable("VaiTro", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.VaiTroQuyen", b =>
                {
                    b.Property<int>("VaiTroId")
                        .HasColumnType("int");

                    b.Property<int>("QuyenId")
                        .HasColumnType("int");

                    b.HasKey("VaiTroId", "QuyenId");

                    b.HasIndex("QuyenId");

                    b.ToTable("VaiTro_Quyen", (string)null);
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.NguoiDungKhoaPhongVaiTro", b =>
                {
                    b.HasOne("QLQTDT.Api.Models.Entities.KhoaPhong", "KhoaPhong")
                        .WithMany("NguoiDungKhoaPhongVaiTros")
                        .HasForeignKey("KhoaPhongId");

                    b.HasOne("QLQTDT.Api.Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany("NguoiDungKhoaPhongVaiTros")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLQTDT.Api.Models.Entities.VaiTro", "VaiTro")
                        .WithMany("NguoiDungKhoaPhongVaiTros")
                        .HasForeignKey("VaiTroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KhoaPhong");

                    b.Navigation("NguoiDung");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.NhaThau", b =>
                {
                    b.HasOne("QLQTDT.Api.Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungId");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("QLQTDT.Api.Models.Entities.NguoiDung", "NguoiDung")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("NguoiDungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.VaiTroQuyen", b =>
                {
                    b.HasOne("QLQTDT.Api.Models.Entities.Quyen", "Quyen")
                        .WithMany("VaiTroQuyens")
                        .HasForeignKey("QuyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QLQTDT.Api.Models.Entities.VaiTro", "VaiTro")
                        .WithMany("VaiTroQuyens")
                        .HasForeignKey("VaiTroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quyen");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.KhoaPhong", b =>
                {
                    b.Navigation("NguoiDungKhoaPhongVaiTros");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.NguoiDung", b =>
                {
                    b.Navigation("NguoiDungKhoaPhongVaiTros");

                    b.Navigation("PasswordResetTokens");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.Quyen", b =>
                {
                    b.Navigation("VaiTroQuyens");
                });

            modelBuilder.Entity("QLQTDT.Api.Models.Entities.VaiTro", b =>
                {
                    b.Navigation("NguoiDungKhoaPhongVaiTros");

                    b.Navigation("VaiTroQuyens");
                });
#pragma warning restore 612, 618
        }
    }
}
